name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        rust: ["1.59", stable, beta, nightly]
        triple: [""]
        include:
        - os: ubuntu-latest
          rust: nightly
          triple: x86_64-unknown-linux-gnu
        - os: macOS-latest
          rust: nightly
          triple: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: "--verbose"
    - name: doc
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: "--verbose"
    - name: build --release
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: "--verbose --release"
    - name: rustup component add rust-src
      run: "rustup component add rust-src --toolchain nightly-${{ matrix.triple }}"
      if: "${{ matrix.triple != '' }}"
    - name: ensure_no_std build
      run: "cargo +nightly build --verbose -Z build-std=core,panic_abort --target ${{ matrix.triple }} --release"
      working-directory: ensure_no_std
      if: "${{ matrix.triple != '' }}"
    - name: ensure_no_std run
      run: "./ensure_no_std/target/${{ matrix.triple }}/release/ensure_no_std"
      if: "${{ matrix.triple != '' }}"
